# Percy visual regression testing configuration
# https://www.browserstack.com/docs/percy/take-percy-snapshots/snapshots-via-cli
version: 2

snapshot:
  widths:
    - 320
    - 393
    - 440
    - 900
    - 901
    - 1200
  min-height: 1024
  percy-css: |
    /* Disable animations and transitions for deterministic snapshots */
    *, *::before, *::after {
      animation-duration: 0s !important;
      animation-delay: 0s !important;
      transition-duration: 0s !important;
      transition-delay: 0s !important;
    }
    /* Hide custom cursor */
    .cursor, .cursor-ring {
      display: none !important;
    }
